language: python

cache:
  directories:
  - "~/.platformio"

install:
- pip install -U platformio

env:
- BOARD=uno
- BOARD=leonardo
- BOARD=megaatmega2560
- BOARD=due
- BOARD=genuino101
- BOARD=zero

script:
- for e in examples/*; do
    platformio ci --board=$BOARD --lib=. $e/*;
  done

notifications:
  flowdock:
    # main team
    - secure: "R886r5moVjveRvHpLUjzUIQYKS3zUOcWcn0K5c0jZ5ivqCn0YKyTRfpe0n4gDPP5qmfmglJJr8oES0JdtQ2IojNzT1CcQ0NWK8cATOJ+EBDhseTS39j2AdsM/iWmvUIYOLEBkEbPMsGzA7Gfh+Y783ua/CSPxDpIKvqQOlPMQUGAn/CT4oH1oEbqRNDq2saDC3XMyNK9OQGlCrjJM65nzb0EVRfWkxPjBEp9yj9q7uhQmy2yZfMqxA+aJRU3nt7/Htb5sCO6vqNrHT1pX5flEKDBKNLCqaPJaim5xIo8R/AoXJegAQd1ig1NuG7TWJ1Qf6FhapGEPl2zWVJYz/FsA70rk/kWBlEI2CzrLOFY5QxC13cOAOAUqI7yNihb1OFQZkDnnImbaCNWoU5I6NvlFB23gG1wFLkNc9AMpw25iJ5b0tElVk1aqhuowJLEd4JAmoGE9icvwi4b3+zsgpIo8cP1XTL7bFDp6t0z0COvO/xQ9xG4jSpfru8xqyLBz4lFGdcEd321unH9ELdZfLLULDnGfBuaUuhNXJERdaEkVonvIe7NK7rIeVLfWi9jq7WiQZxFEHXjTV4yPTNJkr48Ty7fp92ya0j0we0k4ULq+5KYcDvxH/1D3cmScJd8FUbd3C0HQR+ck/IMHpD3sBsbLP9TudeGIA+yy/7RJpM2X8U="
    # software teamc
    - secure: "u4+SvUGUxnF1c7h9VpG9SRLuZ2Y4Y4jFB1lE6xXa/vkVlxD/OsW9dkvr3jXwx6BWC35xdWIiXjx/IsXeu8cliTLrYtJl31olMhN9vY30NicQJgHWQK+bFdYsWpOVR0fXWgzM/8ze0Zj56R1YbU6t6s2EH+waG9yg27m2xiMkVc5rKRbWhdiyIkEW4owwj9JWC5oKqMiQoMrVhhggYJhdeVJ9e4vkARnCqMSwWETrqWRors1bcTRdlNzLaVBsEcgOQ1KidlJnXVRvXLMAgXeAnPmYEE0o+3p0NNdEfakCjMPWymK6RJSAlmWqBGvL/JMQ6rAsaURYhiql4l84E2RfjEQGV/5r+/uTfJNaZZYmTlaLACRPZ7tdGAi2vAYXMW2IXD0ZCkzmvYJ/+Bg5pxFmOLwFoE1zplAvci9gE6lf8UtaDg5H1v2QZpajFGOnfFN8AGOblIlnJTPSDRcyPqm/l9n7kHj/W7gGF6jZl2WeVCPMtQhhGVob9S4n+OPBvadhFT0Gitlq+egu1Q7sQnLS/uflsp5vwSXZswHcMwLhZC4JHDEI9Tv6zQX0KfViTkh7ZyRZlhpG3Nedy5c5PvZppwHuSaDlBr1IEECcQ6peqwurjDktyvUggjPhZiwb33w1PVDabm22SUoIl8kCpagLie+2LamVVPvvedbnLRpp6X4="
